version: '3'

services:
  db:
    image: timescale/timescaledb:latest-pg11
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - '5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    image: woofplot:latest
    environment:
      - DB_URL=jdbc:postgresql://db:5432/
    ports:
      - '8080:8080'
    depends_on:
      - db
    entrypoint: >
      /bin/bash -c "
        failures=0
        while [ $$failures -lt 5 ] && ! timeout 1 bash -c 'cat < /dev/null > /dev/tcp/db/5432'
        do
          echo 'Waiting for database initialization...'
          ((failures++))
          sleep 10
        done
        if [ $$failures -eq 5 ]
        then
          echo 'Did not detect database initialization'
          exit 1
        fi
        echo 'Detected database, starting WoofPlot'
        /opt/docker/bin/woofplot -Dconfig.resource=postgres.conf -Djava.security.egd=file:/dev/./urandom
      "
volumes:
  pgdata: