version: '3'

services:
  db:
    image: timescale/timescaledb:latest-pg11
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - '5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    image: woofplot:latest
    environment:
      - DB_URL=jdbc:postgresql://db:5432/
    ports:
      - '8080:8080'
    depends_on:
      - db
volumes:
  pgdata: